#170947533, #170947534, #170947539 set-up postgres, sequelize and dotenv
andela/devrepublic-bn-backend pull request #1
Opened 2020-02-04 13:40 UTC by bbaime98

#### What does this PR do?
- set-up database with sequelize   and secure their credentials with dotenv
#### Description of Task to be completed?
- install pg and pg-hstore dependencies
- install sequelize, sequelize-cli, and dotenv dependencies
- add  sequelizelrc file
- add config file  with environment variables
#### How should this be manually tested?
- clone repo
- add your postgres credentials in `.env` file
- run `sequelize db:migrate`
- add dummy user in seeder file
- run `sequelize db:seed:all`
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
- [#170947533](https://www.pivotaltracker.com/story/show/170947533)
- [#170947539](https://www.pivotaltracker.com/story/show/170947539)
- [#170947534](https://www.pivotaltracker.com/story/show/170947534)
#### Screenshots (if appropriate)
#### Questions:
- N/A

2020-02-04 14:17 UTC, Ntare22 reviewed
I do not see the migrations, were the files created in the database?

2020-02-04 14:23 UTC, bbaime98 commented
> I do not see the migrations, were the files created in the database?

after setting up both Postgres and sequelize, I used dummy data to test if it works by creating seeders and migrating them. Ultimately I deleted them.

2020-02-05 07:47 UTC, Ntare22 submitted a review, later dismissed

2020-02-05 08:21 UTC, Baraka-Mugisha submitted a review, later dismissed

2020-02-05 12:15 UTC, Mnickii requested changes
Also, let's include the migrations so that we can track any changes, and seeders, and a script to migrate on package.json

2020-02-05 12:15 UTC, Mnickii commented on .sequelizerc
> +}
Add a new line for consistency with other files. You can configure your editor to automatically do this.

2020-02-06 19:01 UTC, Ntare22 submitted a review, later dismissed
Finally man!!

2020-02-06 19:05 UTC, Mnickii requested changes

2020-02-06 19:05 UTC, Mnickii commented on .hound.yml
> -fail_on_violations: true
return this, let it look like this 
```eslint:
  enabled: true
  config_file: .eslintrc.json
  ignore_file: .eslintignore

fail_on_violations: true
```

2020-02-07 07:48 UTC, StevenDerrick approved these changes

2020-02-07 07:49 UTC, bbaime98 commented on .hound.yml
> -fail_on_violations: true
It is fixed.

2020-02-07 08:14 UTC, Baraka-Mugisha approved these changes

2020-02-07 09:06 UTC, Mnickii approved these changes

2020-02-07 10:50 UTC, merged