#170947547 Adds login feature
andela/devrepublic-bn-backend pull request #15
Opened 2020-02-11 11:06 UTC by Baraka-Mugisha

#### What does this PR do?
- create login API endpoint for Barefoot Nomad

#### Description of Task to be completed?
- create a login route at “api/v1/auth/login” `
- add login tests
- add login controllers
- add login routes

#### How should this be manually tested?
- clone the repo
- run `npm install` to install all dependencies
- run the server and go to the above route in POSTMAN

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
- [#170947547](https://www.pivotaltracker.com/story/show/170947547)

#### Screenshots (if appropriate)

<img width="830" alt="Screen Shot 2020-02-11 at 12 46 12" src="https://user-images.githubusercontent.com/41383503/74231364-1c012600-4ccf-11ea-82e7-9884a1f4dc34.png">
<img width="829" alt="Screen Shot 2020-02-11 at 12 46 53" src="https://user-images.githubusercontent.com/41383503/74231374-228f9d80-4ccf-11ea-815c-69e33ed7402c.png">
<img width="1131" alt="Screen Shot 2020-02-11 at 12 44 04" src="https://user-images.githubusercontent.com/41383503/74231394-2b806f00-4ccf-11ea-87fb-f110c3ed1d8b.png">

2020-02-12 07:22 UTC, Ntare22 submitted a review, later dismissed
Why is TravisCi failing? Please look into it?

2020-02-12 07:57 UTC, Mnickii requested changes

2020-02-12 07:57 UTC, Mnickii commented on src/tests/mockData.js
> +  },
Instead of mockData, let's look into seeding the database with data before we run the tests

2020-02-13 14:22 UTC, Mnickii requested changes

2020-02-13 14:22 UTC, Mnickii commented on src/index.js
> +app.use('/api/v1/auth', authRouter);
duplicate

2020-02-13 14:48 UTC, Baraka-Mugisha commented on src/index.js
> +app.use('/api/v1/auth', authRouter);
it is resolved now

2020-02-13 16:52 UTC, Mnickii submitted a review, later dismissed

2020-02-13 18:16 UTC, izzett222 approved these changes

2020-02-13 18:18 UTC, bbaime98 approved these changes

2020-02-13 18:48 UTC, Mnickii approved these changes

2020-02-13 18:49 UTC, merged