#171281019 create email verification tests
andela/devrepublic-bn-backend pull request #21
Opened 2020-02-14 20:32 UTC by Ntare22

#### What does this PR do?
- Create email verification tests
- Create validate parameters file
#### Description of Task to be completed?
- Create verification test file
- Create seeders data for verification
- Write tests to check the controller
#### How should this be manually tested?
-  Clone repository 
- Run `npm install`
- Run `npm test`
#### Any background context you want to provide?
- I added validateParams file to enable us to validate if the parameters passed in a request are valid.
#### What are the relevant pivotal tracker stories?
[#171281019](https://www.pivotaltracker.com/story/show/171281019)
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/30793016/74565448-e7fd5d80-4f79-11ea-95f1-ef57480612cd.png)

2020-02-16 21:06 UTC, bbaime98 submitted a review, later dismissed

2020-02-17 08:28 UTC, izzett222 submitted a review, later dismissed

2020-02-17 10:22 UTC, Mnickii requested changes

2020-02-17 10:22 UTC, Mnickii commented on src/tests/verifyAccountMock.js
> +export const wrongEmail = 'jim@andela';
include a test for a valid user but a wrong email, not wrong email type

2020-02-17 12:12 UTC, Baraka-Mugisha approved these changes

2020-02-17 12:25 UTC, Mnickii approved these changes

2020-02-17 12:40 UTC, izzett222 approved these changes

2020-02-17 12:42 UTC, merged