Ft profile settings 170947551
andela/devrepublic-bn-backend pull request #25
Opened 2020-02-18 10:11 UTC by bbaime98

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-02-19 08:42 UTC, Ntare22 requested changes
I think you should create a separate the functionality of uploading a picture so that we can reuse it in our work.

2020-02-19 11:05 UTC, bbaime98 commented
> I think you should create a separate the functionality of uploading a picture so that we can reuse it in our work.

it is done! check the services folder.

2020-02-19 14:59 UTC, Mnickii commented on .vscode/settings.json
> +    "files.insertFinalNewline": true
gitignore this

2020-02-19 20:26 UTC, Mnickii approved these changes

2020-02-20 09:05 UTC, Baraka-Mugisha approved these changes

2020-02-20 09:05 UTC, izzett222 approved these changes

2020-02-20 09:11 UTC, Ntare22 approved these changes

2020-02-20 10:52 UTC, merged