#170947558 implements reject request feature
andela/devrepublic-bn-backend pull request #37
Opened 2020-02-27 09:07 UTC by bbaime98

#### What does this PR do?
 - add reject request functionality
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
- [#170947558](https://www.pivotaltracker.com/story/show/170947558)
#### Screenshots (if appropriate)
#### Questions:

2020-02-27 17:52 UTC, izzett222 submitted a review, later dismissed

2020-02-28 07:49 UTC, Baraka-Mugisha submitted a review, later dismissed

2020-02-28 14:58 UTC, Ntare22 submitted a review, later dismissed

2020-03-02 08:35 UTC, ceelogre requested changes
Where are the unit tests?

2020-03-02 09:28 UTC, bbaime98 commented
> Where are the unit tests?

I am going to add them.

2020-03-02 10:23 UTC, bbaime98 commented
> Where are the unit tests?

Done!

2020-03-02 10:48 UTC, ceelogre requested changes

2020-03-02 10:48 UTC, ceelogre commented on src/tests/rejectRequest.test.js
> +  }));
Where's assertion?

2020-03-02 10:48 UTC, ceelogre commented on src/tests/rejectRequest.test.js
> +    }
Where's assertion?

2020-03-02 10:48 UTC, ceelogre commented on src/tests/rejectRequest.test.js
> +    assert.equal(requestId, '0ad0ef9d-a926-4c5c-86e6-4d1e22e9ab88');
This is a superficial test as it's value was set on line 11. Unless it was changed by another request.

2020-03-02 12:09 UTC, izzett222 approved these changes

2020-03-02 12:32 UTC, Baraka-Mugisha approved these changes

2020-03-02 12:48 UTC, Ntare22 approved these changes

2020-03-02 13:22 UTC, ceelogre approved these changes

2020-03-02 13:22 UTC, merged