ft(user is able to like/unlike):
andela/devrepublic-bn-backend pull request #40
Opened 2020-02-27 18:33 UTC by Ntare22

#### What does this PR do?
A user is able to like or unlike a facility
#### Description of Task to be completed?
- added the likes column
- added middleware to verify facility
- added to like and unlike methods in the facilitiesController
#### How should this be manually tested?
-
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
[#170947576](https://www.pivotaltracker.com/story/show/170947576)
#### Screenshots (if appropriate)
#### Questions:

2020-03-02 12:19 UTC, bbaime98 commented
can you please add screenshots?

2020-03-02 12:31 UTC, Baraka-Mugisha submitted a review, later dismissed

2020-03-02 12:45 UTC, Ntare22 commented
@bbaime98 I've added some screenshots.

2020-03-02 12:57 UTC, bbaime98 submitted a review, later dismissed

2020-03-02 12:58 UTC, izzett222 approved these changes

2020-03-02 14:06 UTC, ceelogre requested changes
Refactor `facilitiesController` to reduce complexity and add unit tests.

2020-03-02 14:55 UTC, izzett222 requested changes

2020-03-02 14:55 UTC, izzett222 commented on src/services/localesServices/locales/en.json
>  }
could you add an empty line for this file @Ntare22

2020-03-02 14:55 UTC, izzett222 commented on src/controllers/facilitiesController.js
> +      return Response.errorResponse(res, 403, res.__('user has already liked facility'));
hey @Ntare22, shouldn't the like be removed when the user tries to like it two times

2020-03-02 14:55 UTC, izzett222 commented on src/controllers/facilitiesController.js
> +      return Response.errorResponse(res, 403, res.__('user has already unliked facility'));
hey @Ntare22, shouldn't the unlike be removed when the user tries to unlike it two times

2020-03-02 17:52 UTC, izzett222 submitted a review, later dismissed

2020-03-02 17:52 UTC, bbaime98 submitted a review, later dismissed

2020-03-02 17:53 UTC, Baraka-Mugisha submitted a review, later dismissed

2020-03-03 06:55 UTC, ceelogre approved these changes

2020-03-03 06:59 UTC, izzett222 approved these changes

2020-03-03 08:06 UTC, bbaime98 approved these changes

2020-03-03 08:37 UTC, Baraka-Mugisha approved these changes

2020-03-03 09:22 UTC, merged