#170947562 Users get notifications
andela/devrepublic-bn-backend pull request #41
Opened 2020-03-02 13:47 UTC by Baraka-Mugisha

added a table for notification
installed socket.io
[Maintains #170947562]

2020-03-09 08:51 UTC, Ntare22 requested changes
Test coverage has drastically gone down... could you please write more tests especially for io.js file? Make sure not to hit an external API?

2020-03-09 22:25 UTC, Baraka-Mugisha commented
> Test coverage has drastically gone down... could you please write more tests especially for io.js file? Make sure not to hit an external API?

Yeah, I made sure of that. the test coverage has now also come back to normal

2020-03-10 10:06 UTC, izzett222 approved these changes

2020-03-10 10:11 UTC, bbaime98 submitted a review, later dismissed

2020-03-10 10:11 UTC, bbaime98 commented on src/controllers/tripsController.js
> +
why are you rewriting this query? I think we do have it already.

2020-03-10 10:25 UTC, Ntare22 submitted a review, later dismissed

2020-03-10 13:36 UTC, Baraka-Mugisha commented on src/controllers/tripsController.js
> +
I removed it.

2020-03-10 13:37 UTC, Baraka-Mugisha commented on src/controllers/tripsController.js
> +
I didn't recognize that we added user_id attribute to the Requests table before

2020-03-10 13:39 UTC, izzett222 requested changes

2020-03-10 13:39 UTC, izzett222 commented on public/index.html
> +            console.log(data);
@Baraka-Mugisha can you remove console in this file
```suggestion
```

2020-03-10 16:09 UTC, izzett222 submitted a review, later dismissed

2020-03-10 16:47 UTC, bbaime98 submitted a review, later dismissed

2020-03-10 16:58 UTC, Ntare22 submitted a review, later dismissed

2020-03-11 11:24 UTC, bbaime98 submitted a review, later dismissed

2020-03-11 11:24 UTC, izzett222 submitted a review, later dismissed

2020-03-11 12:26 UTC, Ntare22 submitted a review, later dismissed
LGTM

2020-03-11 16:14 UTC, izzett222 approved these changes

2020-03-11 16:20 UTC, bbaime98 approved these changes

2020-03-11 16:33 UTC, Ntare22 approved these changes

2020-03-11 16:56 UTC, merged