#170947581 users are able to chat
andela/devrepublic-bn-backend pull request #53
Opened 2020-03-16 15:51 UTC by Ntare22

#### What does this PR do?
- implements  users are able to chat
#### Description of Task to be completed?
- add chat.html page
- add chat functionality to the ioMiddleware
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-03-19 10:00 UTC, Baraka-Mugisha requested changes

2020-03-19 10:00 UTC, Baraka-Mugisha commented on src/index.js
> +  next();
Could you remove this middleware?

2020-03-19 12:57 UTC, Ntare22 commented on src/index.js
> +  next();
I has been removed!

2020-03-21 07:19 UTC, Baraka-Mugisha commented
Could you add a screenshot to the PR showing this feature?

2020-03-23 10:38 UTC, izzett222 requested changes

2020-03-23 10:38 UTC, izzett222 commented on src/tests/chat.test.js
> +    // done();
could you remove commented code

2020-03-23 10:38 UTC, izzett222 commented on public/chat.html
> +      });
hey @Ntare22 are you using this piece pf code

2020-03-23 11:13 UTC, izzett222 submitted a review, later dismissed

2020-03-23 11:13 UTC, Baraka-Mugisha submitted a review, later dismissed

2020-03-23 11:15 UTC, bbaime98 submitted a review, later dismissed

2020-03-23 15:22 UTC, Baraka-Mugisha submitted a review, later dismissed

2020-03-23 15:25 UTC, bbaime98 requested changes

2020-03-23 15:25 UTC, bbaime98 commented on src/services/localesServices/locales/en.json
> +}
add new line please.

2020-03-23 16:10 UTC, izzett222 submitted a review, later dismissed

2020-03-23 19:38 UTC, bbaime98 commented
Use the following to totally remove package-lock: `git rm --cached package-lock.json` then git add, commit and push.

2020-03-24 09:47 UTC, bbaime98 submitted a review, later dismissed
Great work Jim!

2020-03-24 10:15 UTC, izzett222 approved these changes

2020-03-24 10:15 UTC, Baraka-Mugisha approved these changes

2020-03-24 10:17 UTC, bbaime98 approved these changes

2020-03-24 10:39 UTC, merged